services:
  # 1. 데이터베이스 (MariaDB)
  db:
    image: mariadb:latest # 12.2.2를 포함한 최신 버전 사용
    container_name: yj-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "1234"
      MARIADB_DATABASE: user_db
    ports:
      - "3316:3306"

  # 2. 백엔드 (Spring Boot)
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: ./backend
    container_name: yj-backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  # 3. 프론트엔드 (React)
  frontend:
    build: ./frontend
    container_name: yj-frontend
    ports:
      - "63342:80" # 호스트의 63342 포트를 컨테이너의 80 포트와 연결
    depends_on:
      - backend